Controllers/KontaktFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IntelRobotics.Data;
using IntelRobotics.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace IntelRobotics.Controllers
{
    public class KontaktFormsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public KontaktFormsController(ApplicationDbContext context, UserManager<IdentityUser> userManger, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManger = userManger;
            _roleManager = roleManager;
        }





        // GET: KontaktForms
        public async Task<IActionResult> Index()
        {
            List<KontaktForm> kontaktForms = new List<KontaktForm>();
            var kontaktforms = await _context.kontaktForms.ToListAsync();
            var KontaktTorobot = await _context.kontaktFormToRobots.ToListAsync();
            foreach (var item in kontaktforms)
            {
                var KTR = KontaktTorobot.Where(x => x.KontaktFormId == item.Id);
                if (KTR.Count()>0)
                {
                    var robot = _context.Robots.Where(x => x.Robotid == KTR.FirstOrDefault().RobotId).AsNoTracking();
                    KontaktForm kontaktForm = new KontaktForm()
                    {
                        Id = item.Id,
                        Email = item.Email,
                        CompanyName = item.CompanyName,
                        Name = item.Name,
                        Regarding = item.Regarding,
                        RequestDate = item.RequestDate,
                        RB = robot.FirstOrDefault().Name,
                        RBIMAGE = robot.FirstOrDefault().ImageName,
                    };
                    kontaktForms.Add(kontaktForm);
                }
                else
                {
                    kontaktForms.Add(item);
                }
            }
            return View(kontaktForms);
            
        }

        // GET: KontaktForms/Details/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.kontaktForms == null)
            {
                return NotFound();
            }
            else
            {
                List<KontaktForm> kontaktForms = new List<KontaktForm>();
                var kontaktforms = await _context.kontaktForms.Where(x=>x.Id==id).ToListAsync();
                var KontaktTorobot = await _context.kontaktFormToRobots.ToListAsync();
                foreach (var item in kontaktforms)
                {
                    var KTR = KontaktTorobot.Where(x => x.KontaktFormId == item.Id);
                    if (KTR.Count() > 0)
                    {

                        var robot = _context.Robots.Where(x => x.Robotid == KTR.FirstOrDefault().RobotId).AsNoTracking();
                        KontaktForm kontaktForm = new KontaktForm()
                        {
                            Id = item.Id,
                            Email = item.Email,
                            CompanyName = item.CompanyName,
                            Name = item.Name,
                            Regarding = item.Regarding,
                            RequestDate = item.RequestDate,
                            RB = robot.FirstOrDefault().Name,
                            RBIMAGE = robot.FirstOrDefault().ImageName,

                        };
                        kontaktForms.Add(kontaktForm);
                    }
                    else
                    {
                        kontaktForms.Add(item);
                    }
                }
                ViewData["data"] = kontaktForms.FirstOrDefault() as KontaktForm;
                return View();
            }
            return NotFound();
        }

        // GET: KontaktForms/Create

        public async Task<IActionResult> Create(Guid? id)
        {
            string role = "no";
            var use = _userManger.GetUserName(User);
            var user = _userManger.Users.Where(x => x.UserName == use);
            foreach (var item in user)
            {
                var roles = await _userManger.GetRolesAsync(item);
                if (roles.Count() > 0)
                {
                    role = roles.FirstOrDefault();
                }
            }
            if (role!="no")
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                if (id == null)
                {
                    return View();
                }
                else
                {
                    try
                    {
                        var data = _context.Robots.Where(x => x.Robotid == id);
                        if (data != null)
                        {
                            ViewData["robot"] = data.FirstOrDefault();
                            ViewData["Name"] = data.FirstOrDefault().Name;
                            return View();
                        }
                        return View();
                    }
                    catch (Exception)
                    {
                        return Problem();
                    }
                }
            }
        }

        // POST: KontaktForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,CompanyName,Email,Regarding,Robotid")] KontaktForm kontaktForm)
        {

            if (ModelState.IsValid)
            {
                Guid guid = Guid.Parse("1f46ed45-f49c-4dca-83f6-d956c9344c65");
                if (kontaktForm.Robotid ==guid)
                {
                    DateTime dateTime = DateTime.Now;
                    kontaktForm.RequestDate = dateTime;
                    _context.Add(kontaktForm);
                    await _context.SaveChangesAsync();
                    KontaktFormToRobot robot = new KontaktFormToRobot();
                    robot.KontaktFormId = kontaktForm.Id;
                    Guid gu = kontaktForm.Robotid.Value;
                    robot.RobotId = gu;
                    _context.kontaktFormToRobots.Add(robot);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    DateTime dateTime = DateTime.Now;
                    kontaktForm.RequestDate = dateTime;
                    _context.Add(kontaktForm);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index","Home");
            }
            return View(kontaktForm);
        }

        // GET: KontaktForms/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.kontaktForms == null)
            {
                return NotFound();
            }

            var kontaktForm = await _context.kontaktForms.FindAsync(id);
            if (kontaktForm == null)
            {
                return NotFound();
            }
            return View(kontaktForm);
        }

        // POST: KontaktForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CompanyName,Email,Regarding,RequestDate")] KontaktForm kontaktForm)
        {
            if (id != kontaktForm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kontaktForm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KontaktFormExists(kontaktForm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kontaktForm);
        }

        [Authorize(Policy = "Admin")]
        // GET: KontaktForms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.kontaktForms == null)
            {
                return NotFound();
            }

            var kontaktForm = await _context.kontaktForms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kontaktForm == null)
            {
                return NotFound();
            }

            return View(kontaktForm);
        }

        // POST: KontaktForms/Delete/5
        [Authorize(Policy = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.kontaktForms == null)
            {
                return Problem("Entity set 'ApplicationDbContext.kontaktForms'  is null.");
            }
            var kontaktForm = await _context.kontaktForms.FindAsync(id);
            if (kontaktForm != null)
            {
                _context.kontaktForms.Remove(kontaktForm);
            }
            

Controllers/RobotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IntelRobotics.Data;
using IntelRobotics.Models;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;

namespace IntelRobotics.Controllers
{
    public class RobotsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private IMemoryCache _memoryCache;
        private readonly UserManager<IdentityUser> _userManger;

        public RobotsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IMemoryCache memoryCache, UserManager<IdentityUser> userManger)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _memoryCache = memoryCache;
            _userManger = userManger;
        }







        // GET: Robots
        public async Task<IActionResult> Index()
        {
            string role = "no";
            var use = _userManger.GetUserName(User);
            var user = _userManger.Users.Where(x => x.UserName == use);
            foreach (var item in user)
            {
                var roles = await _userManger.GetRolesAsync(item);
                if (roles.Count()>0)
                {
                    role = roles.FirstOrDefault();
                }
            }
            List<Robot> output;
            output =   _memoryCache.Get<List<Robot>>("robots");
            if (output is null)
            {
                var AllRobots = await _context.Robots.AsNoTracking().ToListAsync();
                _memoryCache.Set("robots", AllRobots, TimeSpan.FromMinutes(10));
                output = _memoryCache.Get<List<Robot>>("robots");
            }
            ViewData["role"] = role;
              return _context.Robots != null ? View(output) :
                          Problem("Entity set 'ApplicationDbContext.Robots'  is null.");
        }

        // GET: Robots/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {

            List<Robot> output;
            output = _memoryCache.Get<List<Robot>>("robots");
            if (id == null || _context.Robots == null || output is null)
            {
                return NotFound();
            }
             
            var robot = await _context.Robots
                .FirstOrDefaultAsync(m => m.Robotid == id);
            if (robot == null)
            {
                return NotFound();
            }

            return View(robot);
        }

        // GET: Robots/Create

        [Authorize(Policy = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Robots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,available,Price,ImageFile,LigtingCapacity,Weight,Footprint,Radius,Parts,Edit")] Robot robot)
        {
            //Save Image to wwwroot/image
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(robot.ImageFile.FileName);
                string extension = Path.GetExtension(robot.ImageFile.FileName);
                robot.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await robot.ImageFile.CopyToAsync(fileStream);
                }
                //Insert record
                robot.Robotid = Guid.NewGuid();
                _context.Add(robot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(robot);
        }

        // GET: Robots/Edit/5

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Robots == null)
            {
                return NotFound();
            }

            var robot = await _context.Robots.FindAsync(id);
            if (robot == null)
            {
                return NotFound();
            }
            return View(robot);
        }

        // POST: Robots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,available,Price,ImageName,LigtingCapacity,Weight,Footprint,Radius,Parts")] Robot robot)
        {
            if (id != robot.Robotid)
            {
                return NotFound();
            }
            DateTime date = DateTime.Now;
            robot.Edit=date;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(robot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RobotExists(robot.Robotid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(robot);
        }

        // GET: Robots/Delete/5

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Robots == null)
            {
                return NotFound();
            }

            var robot = await _context.Robots
                .FirstOrDefaultAsync(m => m.Robotid == id);
            if (robot == null)
            {
                return NotFound();
            }

            return View(robot);
        }

        // POST: Robots/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Policy = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Robots == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Robots'  is null.");
            }
            var robot = await _context.Robots.FindAsync(id);
            var imagepath = Path.Combine(_hostEnvironment.WebRootPath,"image",robot.ImageName);
            if (System.IO.File.Exists(imagepath))
            {
                System.IO.File.Delete(imagepath);
            }
            if (robot != null)
            {
                _context.Robots.Remove(robot);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RobotExists(Guid id)
        {
          return (_context.Robots?.Any(e => e.Robotid == id)).GetValueOrDefault();
        }
    }
}

Views/Robots/Create.cshtml
@model IntelRobotics.Models.Robot

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Robot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="available" /> @Html.DisplayNameFor(model => model.available)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile"/>
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LigtingCapacity" class="control-label"></label>
                <input asp-for="LigtingCapacity" class="form-control" />
                <span asp-validation-for="LigtingCapacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Footprint" class="control-label"></label>
                <input asp-for="Footprint" class="form-control" />
                <span asp-validation-for="Footprint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Radius" class="control-label"></label>
                <input asp-for="Radius" class="form-control" />
                <span asp-validation-for="Radius" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parts" class="control-label"></label>
                <input asp-for="Parts" class="form-control" />
                <span asp-validation-for="Parts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edit" class="control-label"></label>
                <input asp-for="Edit" class="form-control" />
                <span asp-validation-for="Edit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Robots/Delete.cshtml
@model IntelRobotics.Models.Robot

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Robot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.available)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.available)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LigtingCapacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LigtingCapacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Footprint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Footprint)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Radius)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Radius)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Robotid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Robots/Details.cshtml
@model IntelRobotics.Models.Robot

@{
    ViewData["Title"] = "Details";
}
<style>
.bg-secondary {
    margin-left: -7.5%;
    margin-right: 5%;
}
</style>
<div class="bg-light" style="width=100%; height=100%; ">
    <div style="margin-left:10%;">
    <img src="@("~/image/"+Model.ImageName)" style="margin-left:32%" asp-append-version="true" width="250px" height="250px"/>
    <dl class="row" >
        <dt class = "col-sm-2">
            <h1 hidden>@Html.DisplayNameFor(model => model.Name)</h1>
        </dt>
        <dd class = "col-sm-10">
            <h1>@Html.DisplayFor(model => model.Name)</h1>
        </dd>
        <dt class = "col-sm-2">
            <h1 hidden> @Html.DisplayNameFor(model => model.Description)</h1>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    </div>
    <div >
        <h1 style="margin-left: 35%;text-decoration: underline;">Specifications</h1>
    </div>
    <div>
        <table class="table table-striped">

            <tbody>
                <tr>
                    <th scope="row">
                        <td>
                            @Html.DisplayNameFor(model => model.LigtingCapacity):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.LigtingCapacity)
                        </td>
                    </th>
                </tr>
                <tr>
                    <th class="row">
                        <td>
                            @Html.DisplayNameFor(model => model.Weight):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Weight)
                        </td>
                    </th>
                </tr>
                <tr>
                    <th scope="row">
                        <td>
                            @Html.DisplayNameFor(model => model.Footprint):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Footprint)
                        </td>
                    </th>
                </tr>
                <tr>
                    <th scope="row">
                        <td>
                            @Html.DisplayNameFor(model => model.Radius):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Radius)
                        </td>
                    </th>
                </tr>
                                <tr>
                    <th scope="row">
                        <td>
                            @Html.DisplayNameFor(model => model.Parts):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Parts)
                        </td>
                    </th>
                </tr>
                                <tr>
                    <th scope="row">
                        <td>
                            @Html.DisplayNameFor(model => model.available):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.available)
                        </td>
                    </th>
                </tr>
            </tbody>
        </table>
            @if(@User.Identity.IsAuthenticated)
            {
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Edit)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Edit)
            </dd>
            }
        </dl>
    </div>
    <div class="col-md-12">
        @if (@User.Identity.IsAuthenticated)
        {
          <a class="p-2" asp-action="Edit" asp-route-id="@Model?.Robotid">Edit</a>   
        }
        <a class="btn btn-primary p-2" asp-action="Index">Back to List</a>
        <a class="btn btn-success" asp-controller="KontaktForms" asp-action="Create" asp-route-id="@Model?.Robotid" style="float:right;">Kontakt</a>
    </div>
</div>

Views/Robots/Edit.cshtml
@model IntelRobotics.Models.Robot

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Robot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Robotid" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="available" /> @Html.DisplayNameFor(model => model.available)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageName" class="control-label"></label>
                <input asp-for="ImageName" class="form-control" />
                <span asp-validation-for="ImageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LigtingCapacity" class="control-label"></label>
                <input asp-for="LigtingCapacity" class="form-control" />
                <span asp-validation-for="LigtingCapacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Footprint" class="control-label"></label>
                <input asp-for="Footprint" class="form-control" />
                <span asp-validation-for="Footprint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Radius" class="control-label"></label>
                <input asp-for="Radius" class="form-control" />
                <span asp-validation-for="Radius" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parts" class="control-label"></label>
                <input asp-for="Parts" class="form-control" />
                <span asp-validation-for="Parts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edit" class="control-label"></label>
                <input asp-for="Edit" class="form-control" />
                <span asp-validation-for="Edit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}